name: CI - Build Validation
on:
  pull_request:
    branches: [dev]
    
jobs:
  validate-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker build . -t app-test
      
      - name: Verify build output
        run: |
          docker run --rm app-test npm run build
