name: Build image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub (optional, if pushing the image)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t peso-a-peso-app:latest .

      - name: Push Docker image
        run: |
          docker tag peso-a-peso-app:latest ${{ secrets.DOCKER_USERNAME }}/peso-a-peso-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/peso-a-peso-app:latest
