# Nombre del workflow y trigger en push a main
name: Build and Deploy
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout del código
      - uses: actions/checkout@v4

      # Login a Docker Hub con credenciales
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construye y sube imagen a Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/peso-a-peso-app:latest

      # Autenticación con Google Cloud
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Deploy a Cloud Run
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'peso-a-peso-app'
          region: 'southamerica-east1'
          image: '${{ secrets.DOCKER_USERNAME }}/peso-a-peso-app:latest'
